---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: idriss
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: idriss
        tier: backend
        track: stable
    spec:
      containers:
        - name: back
          image: "izerai/backend-tp:1.0-SNAPSHOT"
          ports:
            - name: http
              containerPort: 9797
...