version: '3.3'

services:
  backend:
    image: izerai/backend-tp:1.0-SNAPSHOT
    volumes:
      - ./log/backend:/log
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      mode: replicated
      replicas: 2
    healthcheck:
      test: curl --fail -X POST http://backend:9797 -d "health check ok" || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  frontend:
    image: izerai/frontend-tp:1.0-SNAPSHOT
    ports:
      - 9798:9798
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      mode: replicated
      replicas: 1
    links:
      - backend
    volumes:
      - ./log/frontend:/log
    environment:
      - backend.url=http://backend:9797
    healthcheck:
      test: curl --fail -X GET http://frontend:9798 -d "health check ok" || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s