---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: idriss
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: idriss
        tier: frontend
        track: stable
    spec:
      containers:
        - name: front
          image: "izerai/frontend-tp:1.0-SNAPSHOT"
          ports:
            - name: http
              containerPort: 9798
...